# Site settings
title: chenwei's Blog
description: struggle forward
baseurl: "" 
#change the baseurl to "" if you are using it as your user GitHub Pages
url: "https://chen-ustc.github.io"  


# GitHub User settings
username: chenwei
github_username: chen-ustc
user_description: ''
user_title: ''
email: munchkin213@163.com

# Blog Author settings
author:
  name: chenwei           
  picture:        
  email: munchkin213@163.com           
  description:     
  twitter:
  facebook:
  github: https://github.com/chen-ustc               


# markdown
markdown: kramdown

future: true
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: /:year/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
